/* zoomjoystrong.y — Parser for drawing language zjs using Bison */

%{
#include <stdio.h>
#include <stdlib.h>
#include "zoomjoystrong.h"

int yylex(void);
void yyerror(const char *s);

double var[26];
%}

%union {
    /* int ival; */
    float fval;
    char var;
}

/* Prototype for the lexer generated by Flex */


/* Token declarations (from Flex) */
/* %token <fval> INT  */
%token <fval> FLOAT INT
%token PLUS MINUS MULT DIV              /* single chars */
%token CIRCLE RECTANGLE LINE POINT      /* commands */
%token  <var> VARIABLE                  /* identifier with semantic value */
%token SET_COLOR
%token END_STATEMENT
%token END EQUALS

%type <fval> expr

%left PLUS MINUS MULT DIV 

/* Data type for semantic values */


%%
program:
    statements END
;

statements:  
    /* lines different from statements? */
    | statements statement END_STATEMENT    
;


statement:
    POINT expr expr                     { point($2, $3)}
    | LINE expr expr expr expr          { line($2, $3, $4, $5)}
    | CIRCLE expr expr expr             { circle($2, $3, $4)}
    | RECTANGLE expr expr expr expr     { rectangle($2, $3, $4, $5)}
    | SET_COLOR expr expr expr          {
        // check to see if number values are in range (0-255)
        if (($2 >= 0 && $2 <= 255) && ($3 >= 0 && $3 <= 255) && ($4 >= 0 && $4 <= 255)){
            set_color($2, $3, $4);
        } else {
            // Signal a parse error if the value is out of range
            yyerror("Number is out of range (0-100)");
        }
    }
    ;
    | VARIABLE EQUALS
    | END                               { YYACCEPT; }
;


expr:
    INT
    | FLOAT             {$$ = $1;}
    | VARIABLE          {$$ = var[$1 - 'A']}
    | expr PLUS expr    { $$ = $1 + $3; }
    | expr MINUS expr   { $$ = $1 - $3; }
    | expr MULT expr    { $$ = $1 * $3; }
    | expr DIV expr     { $$ = $1 / $3; }
    /* | '(' expr ')' */
;


%%

int main(void) {
    setup();
    printf("Simple Draw program (Flex + Bison)\n");
    printf("Type expressions and press Enter.\n");
    printf("Example: SET_COLOR 50 100 150;\n\n");
    yyparse();
    printf("Done Parsing\n");
    finish();
    return 0;
}

void yyerror(const char *s) {
    fprintf(stderr, "Error: %s\n", s);
}

///bison -d calc.y      # Generates calc.tab.c and calc.tab.h
//flex calc.l          # Generates lex.yy.c
//gcc calc.tab.c lex.yy.c -o calc -lm
//./calc
//Sample RUn
//Simple Calculator (Flex + Bison)
//Type expressions and press Enter.
// Example: (5 + 3) * 2

// 5 + 3
// = 8.00

// (5 + 3) * 2
// = 16.00

// 7 / 0
// Error: Division by zero!
// = 0.00
